"""Polished Crystal game-specific shop extensions.

Handlers defined here have access to ctx.game_controller (a GameController) and
ctx.session.state (a dict that persists across SelectionStep chains).
"""
from game_shops import register
from src.shop.items import ShopCategory, ShopItem

SHOP_PREFIX="shop.game_specific.pkpcrystal"
TRAINER_PICS_PATH="assets/dynamic/pkpcrystal/trainers"

register("pkpcrystal", [
    # Avatars are mapped to Polished Crystal 3.2.3 indexes
    ShopCategory(
        id="pkpcrystal_avatars",
        label=f"{SHOP_PREFIX}.categories.avatars.label",
        description=f"{SHOP_PREFIX}.categories.avatars.description",
        items_per_page=3,
        items_per_row=1,
        items=[
            ShopItem("capture_avatar", f"{SHOP_PREFIX}.items.capture_avatar.label", 0, {}),
            ShopItem("avatar_carrie", f"{SHOP_PREFIX}.items.avatar_carrie.label", 0, {"path": f"{TRAINER_PICS_PATH}/1.png"}, one_time_purchase=True),
            ShopItem("avatar_cal", f"{SHOP_PREFIX}.items.avatar_cal.label", 0, {"path": f"{TRAINER_PICS_PATH}/2.png"}, one_time_purchase=True),
            ShopItem("avatar_jacky", f"{SHOP_PREFIX}.items.avatar_jacky.label", 0, {"path": f"{TRAINER_PICS_PATH}/3.png"}, one_time_purchase=True),
            ShopItem("avatar_falkner", f"{SHOP_PREFIX}.items.avatar_falkner.label", 100000, {"path": f"{TRAINER_PICS_PATH}/4.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bugsy", f"{SHOP_PREFIX}.items.avatar_bugsy.label", 100000, {"path": f"{TRAINER_PICS_PATH}/5.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_whitney", f"{SHOP_PREFIX}.items.avatar_whitney.label", 100000, {"path": f"{TRAINER_PICS_PATH}/6.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_morty", f"{SHOP_PREFIX}.items.avatar_morty.label", 100000, {"path": f"{TRAINER_PICS_PATH}/7.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_chuck", f"{SHOP_PREFIX}.items.avatar_chuck.label", 100000, {"path": f"{TRAINER_PICS_PATH}/8.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_jasmine", f"{SHOP_PREFIX}.items.avatar_jasmine.label", 100000, {"path": f"{TRAINER_PICS_PATH}/9.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_pryce", f"{SHOP_PREFIX}.items.avatar_pryce.label", 100000, {"path": f"{TRAINER_PICS_PATH}/10.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_clair", f"{SHOP_PREFIX}.items.avatar_clair.label", 100000, {"path": f"{TRAINER_PICS_PATH}/11.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_will", f"{SHOP_PREFIX}.items.avatar_will.label", 100000, {"path": f"{TRAINER_PICS_PATH}/12.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_koga", f"{SHOP_PREFIX}.items.avatar_koga.label", 100000, {"path": f"{TRAINER_PICS_PATH}/13.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bruno", f"{SHOP_PREFIX}.items.avatar_bruno.label", 100000, {"path": f"{TRAINER_PICS_PATH}/14.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_karen", f"{SHOP_PREFIX}.items.avatar_karen.label", 100000, {"path": f"{TRAINER_PICS_PATH}/15.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_champion", f"{SHOP_PREFIX}.items.avatar_champion.label", 100000, {"path": f"{TRAINER_PICS_PATH}/16.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_brock", f"{SHOP_PREFIX}.items.avatar_brock.label", 100000, {"path": f"{TRAINER_PICS_PATH}/17.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_misty", f"{SHOP_PREFIX}.items.avatar_misty.label", 100000, {"path": f"{TRAINER_PICS_PATH}/18.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lt_surge", f"{SHOP_PREFIX}.items.avatar_lt_surge.label", 100000, {"path": f"{TRAINER_PICS_PATH}/19.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_erika", f"{SHOP_PREFIX}.items.avatar_erika.label", 100000, {"path": f"{TRAINER_PICS_PATH}/20.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_janine", f"{SHOP_PREFIX}.items.avatar_janine.label", 100000, {"path": f"{TRAINER_PICS_PATH}/21.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sabrina", f"{SHOP_PREFIX}.items.avatar_sabrina.label", 100000, {"path": f"{TRAINER_PICS_PATH}/22.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_blaine", f"{SHOP_PREFIX}.items.avatar_blaine.label", 100000, {"path": f"{TRAINER_PICS_PATH}/23.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_blue", f"{SHOP_PREFIX}.items.avatar_blue.label", 100000, {"path": f"{TRAINER_PICS_PATH}/24.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_red", f"{SHOP_PREFIX}.items.avatar_red.label", 100000, {"path": f"{TRAINER_PICS_PATH}/25.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_leaf", f"{SHOP_PREFIX}.items.avatar_leaf.label", 100000, {"path": f"{TRAINER_PICS_PATH}/26.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_rival1", f"{SHOP_PREFIX}.items.avatar_rival1.label", 100000, {"path": f"{TRAINER_PICS_PATH}/27.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_rival2", f"{SHOP_PREFIX}.items.avatar_rival2.label", 100000, {"path": f"{TRAINER_PICS_PATH}/28.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lyra1", f"{SHOP_PREFIX}.items.avatar_lyra1.label", 100000, {"path": f"{TRAINER_PICS_PATH}/29.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lyra2", f"{SHOP_PREFIX}.items.avatar_lyra2.label", 100000, {"path": f"{TRAINER_PICS_PATH}/30.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_youngster", f"{SHOP_PREFIX}.items.avatar_youngster.label", 100000, {"path": f"{TRAINER_PICS_PATH}/31.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bug_catcher", f"{SHOP_PREFIX}.items.avatar_bug_catcher.label", 100000, {"path": f"{TRAINER_PICS_PATH}/32.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_camper", f"{SHOP_PREFIX}.items.avatar_camper.label", 100000, {"path": f"{TRAINER_PICS_PATH}/33.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_picnicker", f"{SHOP_PREFIX}.items.avatar_picnicker.label", 100000, {"path": f"{TRAINER_PICS_PATH}/34.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_twins", f"{SHOP_PREFIX}.items.avatar_twins.label", 100000, {"path": f"{TRAINER_PICS_PATH}/35.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_fisher", f"{SHOP_PREFIX}.items.avatar_fisher.label", 100000, {"path": f"{TRAINER_PICS_PATH}/36.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bird_keeper", f"{SHOP_PREFIX}.items.avatar_bird_keeper.label", 100000, {"path": f"{TRAINER_PICS_PATH}/37.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_hiker", f"{SHOP_PREFIX}.items.avatar_hiker.label", 100000, {"path": f"{TRAINER_PICS_PATH}/38.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_grunt_m", f"{SHOP_PREFIX}.items.avatar_grunt_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/39.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_grunt_f", f"{SHOP_PREFIX}.items.avatar_grunt_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/40.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_pokefan_m", f"{SHOP_PREFIX}.items.avatar_pokefan_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/41.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_pokefan_f", f"{SHOP_PREFIX}.items.avatar_pokefan_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/42.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_officer_m", f"{SHOP_PREFIX}.items.avatar_officer_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/43.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_officer_f", f"{SHOP_PREFIX}.items.avatar_officer_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/44.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_nurse", f"{SHOP_PREFIX}.items.avatar_nurse.label", 100000, {"path": f"{TRAINER_PICS_PATH}/45.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_pokemaniac", f"{SHOP_PREFIX}.items.avatar_pokemaniac.label", 100000, {"path": f"{TRAINER_PICS_PATH}/46.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cosplayer", f"{SHOP_PREFIX}.items.avatar_cosplayer.label", 100000, {"path": f"{TRAINER_PICS_PATH}/47.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_super_nerd", f"{SHOP_PREFIX}.items.avatar_super_nerd.label", 100000, {"path": f"{TRAINER_PICS_PATH}/48.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lass", f"{SHOP_PREFIX}.items.avatar_lass.label", 100000, {"path": f"{TRAINER_PICS_PATH}/49.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_beauty", f"{SHOP_PREFIX}.items.avatar_beauty.label", 100000, {"path": f"{TRAINER_PICS_PATH}/50.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bug_maniac", f"{SHOP_PREFIX}.items.avatar_bug_maniac.label", 100000, {"path": f"{TRAINER_PICS_PATH}/51.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_ruin_maniac", f"{SHOP_PREFIX}.items.avatar_ruin_maniac.label", 100000, {"path": f"{TRAINER_PICS_PATH}/52.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_firebreather", f"{SHOP_PREFIX}.items.avatar_firebreather.label", 100000, {"path": f"{TRAINER_PICS_PATH}/53.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_juggler", f"{SHOP_PREFIX}.items.avatar_juggler.label", 100000, {"path": f"{TRAINER_PICS_PATH}/54.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_schoolboy", f"{SHOP_PREFIX}.items.avatar_schoolboy.label", 100000, {"path": f"{TRAINER_PICS_PATH}/55.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_schoolgirl", f"{SHOP_PREFIX}.items.avatar_schoolgirl.label", 100000, {"path": f"{TRAINER_PICS_PATH}/56.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_psychic_t", f"{SHOP_PREFIX}.items.avatar_psychic_t.label", 100000, {"path": f"{TRAINER_PICS_PATH}/57.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_hex_maniac", f"{SHOP_PREFIX}.items.avatar_hex_maniac.label", 100000, {"path": f"{TRAINER_PICS_PATH}/58.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sage", f"{SHOP_PREFIX}.items.avatar_sage.label", 100000, {"path": f"{TRAINER_PICS_PATH}/59.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_medium", f"{SHOP_PREFIX}.items.avatar_medium.label", 100000, {"path": f"{TRAINER_PICS_PATH}/60.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_kimono_girl_naoko", f"{SHOP_PREFIX}.items.avatar_kimono_girl_naoko.label", 100000, {"path": f"{TRAINER_PICS_PATH}/61.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_elder", f"{SHOP_PREFIX}.items.avatar_elder.label", 100000, {"path": f"{TRAINER_PICS_PATH}/62.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sr_and_jr", f"{SHOP_PREFIX}.items.avatar_sr_and_jr.label", 100000, {"path": f"{TRAINER_PICS_PATH}/63.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_couple", f"{SHOP_PREFIX}.items.avatar_couple.label", 100000, {"path": f"{TRAINER_PICS_PATH}/64.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_gentleman", f"{SHOP_PREFIX}.items.avatar_gentleman.label", 100000, {"path": f"{TRAINER_PICS_PATH}/65.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_rich_boy", f"{SHOP_PREFIX}.items.avatar_rich_boy.label", 100000, {"path": f"{TRAINER_PICS_PATH}/66.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lady", f"{SHOP_PREFIX}.items.avatar_lady.label", 100000, {"path": f"{TRAINER_PICS_PATH}/67.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_breeder", f"{SHOP_PREFIX}.items.avatar_breeder.label", 100000, {"path": f"{TRAINER_PICS_PATH}/68.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_baker", f"{SHOP_PREFIX}.items.avatar_baker.label", 100000, {"path": f"{TRAINER_PICS_PATH}/69.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cowgirl", f"{SHOP_PREFIX}.items.avatar_cowgirl.label", 100000, {"path": f"{TRAINER_PICS_PATH}/70.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sailor", f"{SHOP_PREFIX}.items.avatar_sailor.label", 100000, {"path": f"{TRAINER_PICS_PATH}/71.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_swimmer_m", f"{SHOP_PREFIX}.items.avatar_swimmer_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/72.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_swimmer_f", f"{SHOP_PREFIX}.items.avatar_swimmer_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/73.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_burglar", f"{SHOP_PREFIX}.items.avatar_burglar.label", 100000, {"path": f"{TRAINER_PICS_PATH}/74.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_pi", f"{SHOP_PREFIX}.items.avatar_pi.label", 100000, {"path": f"{TRAINER_PICS_PATH}/75.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_scientist", f"{SHOP_PREFIX}.items.avatar_scientist.label", 100000, {"path": f"{TRAINER_PICS_PATH}/76.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_rocket_scientist", f"{SHOP_PREFIX}.items.avatar_rocket_scientist.label", 100000, {"path": f"{TRAINER_PICS_PATH}/77.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_boarder", f"{SHOP_PREFIX}.items.avatar_boarder.label", 100000, {"path": f"{TRAINER_PICS_PATH}/78.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_skier", f"{SHOP_PREFIX}.items.avatar_skier.label", 100000, {"path": f"{TRAINER_PICS_PATH}/79.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_blackbelt_t", f"{SHOP_PREFIX}.items.avatar_blackbelt_t.label", 100000, {"path": f"{TRAINER_PICS_PATH}/80.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_battle_girl", f"{SHOP_PREFIX}.items.avatar_battle_girl.label", 100000, {"path": f"{TRAINER_PICS_PATH}/81.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_dragon_tamer", f"{SHOP_PREFIX}.items.avatar_dragon_tamer.label", 100000, {"path": f"{TRAINER_PICS_PATH}/82.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_engineer", f"{SHOP_PREFIX}.items.avatar_engineer.label", 100000, {"path": f"{TRAINER_PICS_PATH}/83.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_teacher_f", f"{SHOP_PREFIX}.items.avatar_teacher_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/84.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_teacher_m", f"{SHOP_PREFIX}.items.avatar_teacher_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/85.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_guitarist_m", f"{SHOP_PREFIX}.items.avatar_guitarist_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/86.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_guitarist_f", f"{SHOP_PREFIX}.items.avatar_guitarist_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/87.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_biker", f"{SHOP_PREFIX}.items.avatar_biker.label", 100000, {"path": f"{TRAINER_PICS_PATH}/88.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_roughneck", f"{SHOP_PREFIX}.items.avatar_roughneck.label", 100000, {"path": f"{TRAINER_PICS_PATH}/89.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_tamer", f"{SHOP_PREFIX}.items.avatar_tamer.label", 100000, {"path": f"{TRAINER_PICS_PATH}/90.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_artist", f"{SHOP_PREFIX}.items.avatar_artist.label", 100000, {"path": f"{TRAINER_PICS_PATH}/91.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_aroma_lady", f"{SHOP_PREFIX}.items.avatar_aroma_lady.label", 100000, {"path": f"{TRAINER_PICS_PATH}/92.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_soldier", f"{SHOP_PREFIX}.items.avatar_soldier.label", 100000, {"path": f"{TRAINER_PICS_PATH}/93.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_waiter", f"{SHOP_PREFIX}.items.avatar_waiter.label", 100000, {"path": f"{TRAINER_PICS_PATH}/94.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_waitress", f"{SHOP_PREFIX}.items.avatar_waitress.label", 100000, {"path": f"{TRAINER_PICS_PATH}/95.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sightseer_m", f"{SHOP_PREFIX}.items.avatar_sightseer_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/96.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sightseer_f", f"{SHOP_PREFIX}.items.avatar_sightseer_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/97.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_sightseers", f"{SHOP_PREFIX}.items.avatar_sightseers.label", 100000, {"path": f"{TRAINER_PICS_PATH}/98.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cooltrainer_m", f"{SHOP_PREFIX}.items.avatar_cooltrainer_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/99.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cooltrainer_f", f"{SHOP_PREFIX}.items.avatar_cooltrainer_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/100.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_ace_duo", f"{SHOP_PREFIX}.items.avatar_ace_duo.label", 100000, {"path": f"{TRAINER_PICS_PATH}/101.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_veteran_m", f"{SHOP_PREFIX}.items.avatar_veteran_m.label", 100000, {"path": f"{TRAINER_PICS_PATH}/102.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_veteran_f", f"{SHOP_PREFIX}.items.avatar_veteran_f.label", 100000, {"path": f"{TRAINER_PICS_PATH}/103.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_proton", f"{SHOP_PREFIX}.items.avatar_proton.label", 100000, {"path": f"{TRAINER_PICS_PATH}/104.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_petrel", f"{SHOP_PREFIX}.items.avatar_petrel.label", 100000, {"path": f"{TRAINER_PICS_PATH}/105.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_archer", f"{SHOP_PREFIX}.items.avatar_archer.label", 100000, {"path": f"{TRAINER_PICS_PATH}/106.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_ariana", f"{SHOP_PREFIX}.items.avatar_ariana.label", 100000, {"path": f"{TRAINER_PICS_PATH}/107.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_giovanni", f"{SHOP_PREFIX}.items.avatar_giovanni.label", 100000, {"path": f"{TRAINER_PICS_PATH}/108.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_oak", f"{SHOP_PREFIX}.items.avatar_oak.label", 100000, {"path": f"{TRAINER_PICS_PATH}/109.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_elm", f"{SHOP_PREFIX}.items.avatar_elm.label", 100000, {"path": f"{TRAINER_PICS_PATH}/110.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_ivy", f"{SHOP_PREFIX}.items.avatar_ivy.label", 100000, {"path": f"{TRAINER_PICS_PATH}/111.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_mysticalman", f"{SHOP_PREFIX}.items.avatar_mysticalman.label", 100000, {"path": f"{TRAINER_PICS_PATH}/112.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_karate_king", f"{SHOP_PREFIX}.items.avatar_karate_king.label", 100000, {"path": f"{TRAINER_PICS_PATH}/113.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_towertycoon", f"{SHOP_PREFIX}.items.avatar_towertycoon.label", 100000, {"path": f"{TRAINER_PICS_PATH}/114.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_factoryhead", f"{SHOP_PREFIX}.items.avatar_factoryhead.label", 100000, {"path": f"{TRAINER_PICS_PATH}/115.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_jessie_james", f"{SHOP_PREFIX}.items.avatar_jessie_james.label", 100000, {"path": f"{TRAINER_PICS_PATH}/116.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lorelei", f"{SHOP_PREFIX}.items.avatar_lorelei.label", 100000, {"path": f"{TRAINER_PICS_PATH}/117.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_agatha", f"{SHOP_PREFIX}.items.avatar_agatha.label", 100000, {"path": f"{TRAINER_PICS_PATH}/118.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_steven", f"{SHOP_PREFIX}.items.avatar_steven.label", 100000, {"path": f"{TRAINER_PICS_PATH}/119.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cynthia", f"{SHOP_PREFIX}.items.avatar_cynthia.label", 100000, {"path": f"{TRAINER_PICS_PATH}/120.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_inver", f"{SHOP_PREFIX}.items.avatar_inver.label", 100000, {"path": f"{TRAINER_PICS_PATH}/121.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cheryl", f"{SHOP_PREFIX}.items.avatar_cheryl.label", 100000, {"path": f"{TRAINER_PICS_PATH}/122.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_riley", f"{SHOP_PREFIX}.items.avatar_riley.label", 100000, {"path": f"{TRAINER_PICS_PATH}/123.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_buck", f"{SHOP_PREFIX}.items.avatar_buck.label", 100000, {"path": f"{TRAINER_PICS_PATH}/124.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_marley", f"{SHOP_PREFIX}.items.avatar_marley.label", 100000, {"path": f"{TRAINER_PICS_PATH}/125.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_mira", f"{SHOP_PREFIX}.items.avatar_mira.label", 100000, {"path": f"{TRAINER_PICS_PATH}/126.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_anabel", f"{SHOP_PREFIX}.items.avatar_anabel.label", 100000, {"path": f"{TRAINER_PICS_PATH}/127.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_darach", f"{SHOP_PREFIX}.items.avatar_darach.label", 100000, {"path": f"{TRAINER_PICS_PATH}/128.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_caitlin", f"{SHOP_PREFIX}.items.avatar_caitlin.label", 100000, {"path": f"{TRAINER_PICS_PATH}/129.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_candela", f"{SHOP_PREFIX}.items.avatar_candela.label", 100000, {"path": f"{TRAINER_PICS_PATH}/130.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_blanche", f"{SHOP_PREFIX}.items.avatar_blanche.label", 100000, {"path": f"{TRAINER_PICS_PATH}/131.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_spark", f"{SHOP_PREFIX}.items.avatar_spark.label", 100000, {"path": f"{TRAINER_PICS_PATH}/132.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_flannery", f"{SHOP_PREFIX}.items.avatar_flannery.label", 100000, {"path": f"{TRAINER_PICS_PATH}/133.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_maylene", f"{SHOP_PREFIX}.items.avatar_maylene.label", 100000, {"path": f"{TRAINER_PICS_PATH}/134.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_marlon", f"{SHOP_PREFIX}.items.avatar_marlon.label", 100000, {"path": f"{TRAINER_PICS_PATH}/135.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_valerie", f"{SHOP_PREFIX}.items.avatar_valerie.label", 100000, {"path": f"{TRAINER_PICS_PATH}/136.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_kukui", f"{SHOP_PREFIX}.items.avatar_kukui.label", 100000, {"path": f"{TRAINER_PICS_PATH}/137.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_piers", f"{SHOP_PREFIX}.items.avatar_piers.label", 100000, {"path": f"{TRAINER_PICS_PATH}/138.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_katy", f"{SHOP_PREFIX}.items.avatar_katy.label", 100000, {"path": f"{TRAINER_PICS_PATH}/139.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_victor", f"{SHOP_PREFIX}.items.avatar_victor.label", 100000, {"path": f"{TRAINER_PICS_PATH}/140.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_bill", f"{SHOP_PREFIX}.items.avatar_bill.label", 100000, {"path": f"{TRAINER_PICS_PATH}/141.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_yellow", f"{SHOP_PREFIX}.items.avatar_yellow.label", 100000, {"path": f"{TRAINER_PICS_PATH}/142.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_walker", f"{SHOP_PREFIX}.items.avatar_walker.label", 100000, {"path": f"{TRAINER_PICS_PATH}/143.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_imakuni", f"{SHOP_PREFIX}.items.avatar_imakuni.label", 100000, {"path": f"{TRAINER_PICS_PATH}/144.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_lawrence", f"{SHOP_PREFIX}.items.avatar_lawrence.label", 100000, {"path": f"{TRAINER_PICS_PATH}/145.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_rei", f"{SHOP_PREFIX}.items.avatar_rei.label", 100000, {"path": f"{TRAINER_PICS_PATH}/146.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_omastar_fossil", f"{SHOP_PREFIX}.items.avatar_omastar_fossil.label", 100000, {"path": f"{TRAINER_PICS_PATH}/147.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_kabutops_fossil", f"{SHOP_PREFIX}.items.avatar_kabutops_fossil.label", 100000, {"path": f"{TRAINER_PICS_PATH}/148.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_aerodactyl_fossil", f"{SHOP_PREFIX}.items.avatar_aerodactyl_fossil.label", 100000, {"path": f"{TRAINER_PICS_PATH}/149.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_cubone_armor", f"{SHOP_PREFIX}.items.avatar_cubone_armor.label", 100000, {"path": f"{TRAINER_PICS_PATH}/150.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_meteorite", f"{SHOP_PREFIX}.items.avatar_meteorite.label", 100000, {"path": f"{TRAINER_PICS_PATH}/151.png"}, one_time_purchase=True, secret=True),
            ShopItem("avatar_silhouette", f"{SHOP_PREFIX}.items.avatar_silhouette.label", 100000, {"path": f"{TRAINER_PICS_PATH}/152.png"}, one_time_purchase=True, secret=True),
        ],
    )
])
