BATTLE_STRUCT_SIZE = 42
PARTY_STRUCT_SIZE = 48

B_SPECIES = 0
B_ITEM = 1
B_MOVES = 2
B_MOVES_LEN = 4
B_DVS = 6
B_DVS_LEN = 3
B_NATURE = 9
B_FORM = 10
B_PP = 11
B_PP_LEN = 4
B_HAPPINESS = 15
B_LEVEL = 16
B_STATUS = 17
B_UNUSED = 18
B_HP = 19
B_HP_LEN = 2
B_MAXHP = 21
B_MAXHP_LEN = 2
B_ATTACK = 23
B_DEFENSE = 25
B_SPEED = 27
B_SPATK = 29
B_SPDEF = 31
STATS_LEN = 2

P_SPECIES = 0
P_ITEM = 1
P_MOVES = 2
P_MOVES_LEN = 4
P_ID = 6
P_ID_LEN = 2
P_EXP = 8
P_EXP_LEN = 3
P_EVS = 11
P_EVS_LEN = 6
P_DVS = 17
P_DVS_LEN = 3
P_NATURE = 20
P_FORM = 21
P_PP = 22
P_PP_LEN = 4
P_HAPPINESS = 26
P_POKERUS = 27
P_CAUGHT_BALL = 28
P_CAUGHT_LEVEL = 29
P_CAUGHT_LOCATION = 30
P_LEVEL = 31
P_STATUS = 32
P_UNUSED2 = 33
P_HP = 34
P_HP_LEN = 2
P_MAXHP = 36
P_MAXHP_LEN = 2
P_ATTACK = 38
P_DEFENSE = 40
P_SPEED = 42
P_SPATK = 44
P_SPDEF = 46

def battle_struct_to_party(data: bytes) -> bytes:
    buf = bytearray(PARTY_STRUCT_SIZE)
    buf[P_SPECIES] = data[B_SPECIES]
    buf[P_ITEM] = data[B_ITEM]
    buf[P_MOVES:P_MOVES + P_MOVES_LEN] = data[B_MOVES:B_MOVES + B_MOVES_LEN]
    buf[P_DVS:P_DVS + P_DVS_LEN] = data[B_DVS:B_DVS + B_DVS_LEN]
    buf[P_NATURE] = data[B_NATURE]
    buf[P_FORM] = data[B_FORM]
    buf[P_PP:P_PP + P_PP_LEN] = data[B_PP:B_PP + B_PP_LEN]
    buf[P_HAPPINESS] = data[B_HAPPINESS]
    buf[P_LEVEL] = data[B_LEVEL]
    buf[P_STATUS] = 0
    buf[P_UNUSED2] = 0
    maxhp_lo = data[B_MAXHP]
    maxhp_hi = data[B_MAXHP + 1]
    buf[P_HP] = maxhp_lo
    buf[P_HP + 1] = maxhp_hi
    buf[P_MAXHP] = maxhp_lo
    buf[P_MAXHP + 1] = maxhp_hi
    buf[P_ATTACK:P_ATTACK + STATS_LEN] = data[B_ATTACK:B_ATTACK + STATS_LEN]
    buf[P_DEFENSE:P_DEFENSE + STATS_LEN] = data[B_DEFENSE:B_DEFENSE + STATS_LEN]
    buf[P_SPEED:P_SPEED + STATS_LEN] = data[B_SPEED:B_SPEED + STATS_LEN]
    buf[P_SPATK:P_SPATK + STATS_LEN] = data[B_SPATK:B_SPATK + STATS_LEN]
    buf[P_SPDEF:P_SPDEF + STATS_LEN] = data[B_SPDEF:B_SPDEF + STATS_LEN]
    return bytes(buf)
